### ISSUE TITLE
Blank empty row when downloading

### ISSUE THREAD

**Issue by Sopor-** [jwensley2/DownloadStatusBar#1]
I only see a small row when i download and when it is finished i see a my download in the status bar. Should it really work like this? I want it to show the downloads more like Chrome does.

This is what i see when i download:
![image](https://user-images.githubusercontent.com/5789283/33515914-8aaa86a6-d769-11e7-952e-03b964cfc18f.png)

I'm running WX Download Status Bar 1.5.0 and Firefox 57.0.1 64-bit

**Comment by jwensley2** [comment]
I think this should be fixed in 1.5.1, please let me know if it fixes it for you or not.

**Comment by Sopor-** [comment]
Yes, it seems to be fixed, but now it get stuck visible mode when i cancel a download... I have tryed to press clear but nothing happens. If i open the context menu and press Clear download it seems to work. Shouldn't the Clear button to the left clear all kinds of cancelled and finished progress?

![image](https://user-images.githubusercontent.com/5789283/33518635-55926e78-d798-11e7-90bd-0ac55aed6ee0.png)

**Comment by Sopor-** [comment]
I also noticed it is possible to clear download when i have paused a download, so it will be very hard to unpause it if the progress disappear :(

**Comment by jwensley2** [comment]
Thanks for the update, good that it fixed your issue.

> Shouldn't the Clear button to the left clear all kinds of cancelled and finished progress?

That would probably make sense, I'll change that for the next version.

> I also noticed it is possible to clear download when i have paused a download, so it will be very hard to unpause it if the progress disappear :(

I assume you mean from the context menu? I wasn't really sure if people would want that option or not so I left it in. You can always resume using the download list `Ctrl+J`.

**Comment by Sopor-** [comment]
If i do that your download status bar won't get back when i resume.
