### ISSUE TITLE
REQUEST: Ignore files on pattern, not only on type

### ISSUE THREAD

**Issue by MarcWeustink** [jwensley2/DownloadStatusBar#103]
Hi, I'm using simple tab groups and this extention backups its config every day. This backup is shown in the status bar as download of 'stg-backup-2019-01-27@drive4ik.json'. Since FF is almost always running, it fills my status bar. I've tried to add stg-backup*.* as type but that doesn't work

Thanks Marc

**Comment by jwensley2** [comment]
This should work as of 1.10.0
