### ISSUE TITLE
Bug on height

### ISSUE THREAD

**Issue by tubo28** [jwensley2/DownloadStatusBar#11]
The height of status bar changes in some pages.
For example: https://www.ubuntu.com/download/desktop/thank-you?country=US&version=16.04.3&architecture=amd64
\* Download of 1.5 GB iso starts when you click this link.

Normal:
![screenshot from 2017-12-07 15-46-49](https://user-images.githubusercontent.com/3405886/33702200-eec14210-db65-11e7-94a9-04abbffc1a53.png)

In above URL page:
![screenshot from 2017-12-07 15-46-52](https://user-images.githubusercontent.com/3405886/33702201-eefdae30-db65-11e7-88b0-9b1ad9711cdb.png)

Versins:
- WX Download Status Bar 1.5.2
- Firefox 57.0.1 (64-bit)
- Ubuntu 16.04 64 bit

**Comment by jwensley2** [comment]
Looks like this is already fixed in the beta version.

https://addons.mozilla.org/en-US/firefox/addon/wx-download-status-bar/versions/beta?page=1#version-1.6.0beta1
