### ISSUE TITLE
Not working with the latest Ff beta versions (70.x)

### ISSUE THREAD

**Issue by misticx** [jwensley2/DownloadStatusBar#119]
Don't know why but plugin stopped working as soon i updated to the latest beta version.

**Comment by jwensley2** [comment]
There is a bug in the beta version of Firefox causing this. I have an open bug report for it here https://bugzilla.mozilla.org/show_bug.cgi?id=1581270

I'm guessing this will get fixed at some point during the 70 beta, if not I'll have to find a work around when it's released.

**Comment by misticx** [comment]
Thank you on that ultra fast answer.

**Comment by molitar** [comment]
So does an earlier version of the beta 70 have this issue fixed? If not I need to go back to version 69.

**Comment by jwensley2** [comment]
This seems to have been fixed in the release version of 70.

**Comment by misticx** [comment]
Yes it was. Thanks anyway.
