### ISSUE TITLE
Addon stops Website from working

### ISSUE THREAD

**Issue by LarryGT** [jwensley2/DownloadStatusBar#137]
When this addon is installed the website filecrypt.cc is no longer working.

**Comment by Qu1goN** [comment]
Yep same problem here, would be cool if this can be fixed - love this Addon ^^

**Comment by Qu1goN** [comment]
Hello, someone here? Please, please fix this one more thing ^^

**Comment by Qu1goN** [comment]
Hope this will be fixed soon please. I still use the addon, there is no better one for me :-)

Hope the video helps.

https://github.com/jwensley2/DownloadStatusBar/assets/62997079/a7099545-3786-4417-a128-bbbd9977dfa6

**Comment by Qu1goN** [comment]
Sorry, Firefox had not yet updated to the new version. Looks like it's working now.

Thank you very much, I'm happy.
