### ISSUE TITLE
where is the text?

### ISSUE THREAD

**Issue by Sopor-** [jwensley2/DownloadStatusBar#22]
This happened to me. I can't see what i was downloading..

![image](https://user-images.githubusercontent.com/5789283/34085130-14045aca-e38c-11e7-8a30-fe84954ee912.png)

**Comment by jwensley2** [comment]
Probably a styling conflict with whatever page you were on. If you can remember what website you were on that might make it easier to fix.

**Comment by Sopor-** [comment]
Press the [DOWNLOAD!](https://www.upload.ee/files/5051/accident22.gif.html) button...
