### ISSUE TITLE
Progress thumper gone crazy

### ISSUE THREAD

**Issue by nicktech** [jwensley2/DownloadStatusBar#23]
Firefox 57.0.1 on MacOS, and the status bar downloading animation is pretty crazy. Sometimes it twirls around the progress text. Sometimes it seems like the animation is split in half and alternates between the right/left side of the screen. 
See this screencast: https://www.dropbox.com/s/l8qhmmdcq5d98hk/crazydownload.mov?dl=0
 
Thanks a bunch!

**Comment by jwensley2** [comment]
Looks like a conflict with the CSS on whatever website that was on. Can you provide a link to the website you were on?

**Comment by nicktech** [comment]
In that particular case I cannot as it is an internal work database. But I have seen it happen out on the public web. Next time it happens I'll give you the URL.

**Comment by jwensley2** [comment]
This should be fixed in the 1.7, there is a beta if want to try it.

https://addons.mozilla.org/en-US/firefox/addon/wx-download-status-bar/versions/beta?page=1#version-1.7.0beta1

**Comment by nicktech** [comment]
Thanks!
The beta seems to have fixed the issue. I tested it on the same site I originally saw the error and everything looks good.
