### ISSUE TITLE
Very long space before the first download

### ISSUE THREAD

**Issue by Sopor-** [jwensley2/DownloadStatusBar#27]
I have no idea what is happening here.. For some reason there will be a very long space as you can see.

![image](https://user-images.githubusercontent.com/5789283/34270228-bddf8fda-e687-11e7-8141-551062942dd3.png)

**Comment by jwensley2** [comment]
Did this happen on a specific website or did it show up on multiple? It looks like it could be a CSS conflict with a website, but I'm not 100% sure.

**Comment by Sopor-** [comment]
It seems to happens on dailyuploads
