### ISSUE TITLE
Scroll issue

### ISSUE THREAD

**Issue by JohnnyB27** [jwensley2/DownloadStatusBar#33]
I can not scroll to the bottom of www.worldoftrucks.com. (All other Addons are disabled)
DownloadStatusBar is enabled:
![ex_001_25122017_220605](https://user-images.githubusercontent.com/34843151/34342922-e0827c4c-e9bf-11e7-841d-35936b5c987e.png)
DownloadStatusBar is disabled:
![ex_002_25122017_220620](https://user-images.githubusercontent.com/34843151/34342923-e09dd640-e9bf-11e7-8eed-7b62ba588095.png)

**Comment by jwensley2** [comment]
Should be fixed in 1.7.0, which there is a beta version of if you want to test it.

https://addons.mozilla.org/en-US/firefox/addon/wx-download-status-bar/versions/beta
