### ISSUE TITLE
no additional info showing up when pointer over the bar

### ISSUE THREAD

**Issue by Sopor-** [jwensley2/DownloadStatusBar#34]
When i hold the mouse pointer over the download bar i will see additional info about the file but on some sites i don't get any.

![image](https://user-images.githubusercontent.com/5789283/34393921-5919c290-eb56-11e7-9167-dc701375fa4b.png)

The pages it won't work on are https://uploadgig.com and https://www.digitalocean.com

![image](https://user-images.githubusercontent.com/5789283/34393928-606d9fee-eb56-11e7-95e2-a55261b54481.png)

**Comment by jwensley2** [comment]
This and #27 should be fixed in the latest beta.
