### ISSUE TITLE
Enhancement: clear DL history when clearing status bar

### ISSUE THREAD

**Issue by DrMoish** [jwensley2/DownloadStatusBar#37]
Currently, clearing the Download StatusBar does not clear the history. It would be helpful to have the option to do both with one click.

**Comment by jwensley2** [comment]
I've added this for the next version, but it probably won't work the way you are expecting.

It seems it only clears the history you see when clicking the downloads button on the toolbar and not the history you see using CTRL+J.

This is a Firefox issue and there is a bug report to fix it, but it's over 2 years old, so it may not be fixed anytime soon.
