### ISSUE TITLE
Firefox for Android 57

### ISSUE THREAD

**Issue by davidhedlund** [jwensley2/DownloadStatusBar#41]
I cannot install WX Download Status Bar in Firefox for Android 57.0.4 despite that the latest version 1.7.1 listed at https://addons.mozilla.org/en-US/firefox/addon/cisco-webex-extension/versions/ says "Firefox for Android 48.0 and later"

**Comment by jwensley2** [comment]
I don't know why the versions page says it works on Android, I don't release for Android because I don't have any Android devices and therefore don't test on it. I'm guessing that page is just displaying incorrect information.

**Comment by davidhedlund** [comment]
> I'm guessing that page is just displaying incorrect information.

Can you please help me figure out this? If it's a bug on addons.mozilla.org then more people will eventually be affected.
