### ISSUE TITLE
can this be fixed?

### ISSUE THREAD

**Issue by Sopor-** [jwensley2/DownloadStatusBar#42]
On this page the DSB will be totally hidden in the left bottom corner http://unetbootin.github.io Try download a file and you will see.
I can still see some green from the bar
![image](https://user-images.githubusercontent.com/5789283/35183474-6bea7e5c-fde7-11e7-970a-98876e49c5ba.png)
![image](https://user-images.githubusercontent.com/5789283/35183481-89ca2b52-fde7-11e7-80de-cf24b210e596.png)

**Comment by hopalongrock** [comment]
I can confirm this. It is noteworthy that the speed and the size (%) are displayed in the same place (see the attachmenr of the original message too) and there is a blank space under them. Previously two download info were appeared there.
![d](https://user-images.githubusercontent.com/6840865/35184829-1246ea02-fdfb-11e7-85bf-1cafb85097ff.jpg)
