### ISSUE TITLE
Autohide doesn't work, I have to Clear

### ISSUE THREAD

**Issue by hopalongrock** [jwensley2/DownloadStatusBar#43]
I specified png jpg and xpi to auto hide after 5 sec, 

![image](https://user-images.githubusercontent.com/6840865/35184986-07fe22f2-fdfd-11e7-95b6-a3a9799792b6.png)

![image](https://user-images.githubusercontent.com/6840865/35185003-4b9e8aa6-fdfd-11e7-9843-b823d819311d.png)

**Comment by jwensley2** [comment]
I'm not sure what could be happening here.

If you don't select any file types does it work? By that I mean does it auto hide everything?

**Comment by hopalongrock** [comment]
With the new version 1.7.2  now both the size and the speed / % is displayed, and  auto hide happens if no file type is selected, or other file types are selected and downloaded, for example rar , png and jpg .

However for xpi ( specified as other file type ) auto hide still doesn't work.

![image](https://user-images.githubusercontent.com/6840865/35198988-641da2e2-fef7-11e7-896a-3266d49d3169.png)

![screenhunter_85 jan 21 21 59](https://user-images.githubusercontent.com/6840865/35198944-d45ff4c0-fef6-11e7-82ae-355498904cf3.jpg)

**Comment by jwensley2** [comment]
Should be fixed whenever I release the next version.
