### ISSUE TITLE
when i clear downloads all running downloads will also disappear

### ISSUE THREAD

**Issue by Sopor-** [jwensley2/DownloadStatusBar#44]
If i want to clear my finished downloads and i have running downloads all the running downloads will be also be cleared. I believe it should only clear the finished and those i have canceled and not the running downloads.

**Comment by jwensley2** [comment]
Running downloads shouldn't be cleared unless you clear that specific download using the context menu.

I'm not sure why it would be clearing running downloads for you.

**Comment by Sopor-** [comment]
Strange, now it works as it should.
