### ISSUE TITLE
Feature request: renaming files on the fly

### ISSUE THREAD

**Issue by wisedevman** [jwensley2/DownloadStatusBar#46]
Very useful component!

Can you add a context menu item to rename the downloaded files directly in firefox?
Even better would be click and rename, but I don't know if it'd be possible.

Thank you!!

**Comment by jwensley2** [comment]
This is not possible, at least not with the current API.

If Mozilla ever adds a way to do it into the API I could probably build it in pretty easily.

**Comment by wisedevman** [comment]
Ok, thank you!
I hope they'll do an enhanced version for power-users (I also miss tabgroups)!
