### ISSUE TITLE
translate "description" ?

### ISSUE THREAD

**Issue by Sopor-** [jwensley2/DownloadStatusBar#48]
I noticed you have added locales. So I wondering if the "description" also should be translated?

**Comment by jwensley2** [comment]
It does not need to be translated, it's just to help translators.

You can read about the format [here](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/i18n/Locale-Specific_Message_reference) and [here](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Internationalization), it's Firefox's built in translation system for web extensions.
