### ISSUE TITLE
status bar change size when i change tab

### ISSUE THREAD

**Issue by Sopor-** [jwensley2/DownloadStatusBar#50]
I still have some issues with the size of status bar. It will change size when i change tab in Firefox. It seems to change the color too so it will be hard to read the Clear button.
![image](https://user-images.githubusercontent.com/5789283/36381609-76650c42-1586-11e8-82c2-3488e9f0bbc1.png)

**Comment by jwensley2** [comment]
Please post the site from the right image, looks like a styling conflict with the website.

**Comment by Sopor-** [comment]
It seems to happen on [this site](https://www.entertainmentbox.com/latest-mxiii-g-ii-tv-box-android-6-0-firmware-download/)

**Comment by Sopor-** [comment]
The bar will still change size. One i found is https://dailyuploads.net

**Comment by Sopor-** [comment]
The bar will still change size. Here is another one https://askubuntu.com

**Comment by Sopor-** [comment]
The status bar is still changing height when i change tab and i have a page open on https://stackoverflow.com

**Comment by Sopor-** [comment]
This can't be fixed... Check this out:
![image](https://user-images.githubusercontent.com/5789283/41247435-427144fc-6dae-11e8-996e-4613f43fe113.png)

I was downloading latest [Ubuntu Desktop](https://www.ubuntu.com/download/desktop)
