### ISSUE TITLE
i wondering if there is a way to get the DSB visible on empty tabs?

### ISSUE THREAD

**Issue by Sopor-** [jwensley2/DownloadStatusBar#51]
I have a few programs i download directly by double clicking on a URL file or open in the Bookmark menu. When i do this the `Download Status Bar` will not show up so it is easy to think that something is wrong:
\- "Why will the download not start?"
So i wondering if there is a way to get the DSB visible on empty tabs? Maybe it is possible to show it somewhere else? As it is now it only make you confused when you don't see a thing of the download :(

**Comment by jwensley2** [comment]
Nothing I can do about it until there is a toolbar api.
