### ISSUE TITLE
Play sound when download finishes

### ISSUE THREAD

**Issue by jwensley2** [jwensley2/DownloadStatusBar#6]
Add an option to play a sound when a download finishes and if possible allow a custom sound to be used.

**Comment by Yoda2017** [comment]
Adding a custom notification sound for finished download would be great.

**Comment by jwensley2** [comment]
@Yoda2017 I've released a beta version with this if you would like to test it out. https://addons.mozilla.org/en-US/firefox/addon/wx-download-status-bar/versions/beta

**Comment by Yoda2017** [comment]
Great Job!! Works perfectly!
I did a lot of tests with multiple downloads!
Thank you.
