### ISSUE TITLE
Korean translation

### ISSUE THREAD

**Issue by ensi0** [jwensley2/DownloadStatusBar#62]
[korean.txt](https://github.com/jwensley2/DownloadStatusBar/files/1792964/korean.txt)

I do not know how to use github and upload it to txt file.

**Comment by jwensley2** [comment]
You will probably need to create a pull request, that file looks like random characters to me, so either the encoding is messed up or I don't have the fonts to display it. Whichever it is I can't tell if it's right so if I do it myself it may end up all screwed up.

There is a guide on how to fork a repo and create a pull request, https://guides.github.com/activities/forking/.
