### ISSUE TITLE
In progress: CRASH

### ISSUE THREAD

**Issue by Sopor-** [jwensley2/DownloadStatusBar#64]
I sometimes get this in the DSB. So what is it that has crashed?

![image](https://user-images.githubusercontent.com/5789283/37418576-d2d9ccc2-27b2-11e8-9b0b-0f25d347a1ab.png)

**Comment by Sopor-** [comment]
It seems to happen when it has downloaded the file and it is about to rename it to the original file name. So `filename.zip` is 0 byte and then i have another file `filename.zip.part` and when it show this CRASH i have both files there. I then delete `filename.zip` and rename `filename.zip.part` to `filename.zip` and to know the file is not corrupt i do a verify on the zip file and it shows the file is OK.

**Comment by jwensley2** [comment]
Closing this since it's not actually an issue with the addon, and I fixed the status showing the wrong message.
