### ISSUE TITLE
Zooming a webpage also zooms the status bar

### ISSUE THREAD

**Issue by ElektroStudios** [jwensley2/DownloadStatusBar#80]
The size of the status bar increase when you increase the webpage zoom, so if you are in a website with a zoom of 150% then you end getting a big, biiiiiig status bar.

Please, could you fix it?. Thanks for read.

**Comment by jwensley2** [comment]
It's not possible to disable zoom for the status bar.
The bar is a part of the webpage and there isn't a way to prevent zooming in a specific part of a page.
