### ISSUE TITLE
Keep downloads in one line

### ISSUE THREAD

**Issue by Komanc** [jwensley2/DownloadStatusBar#9]
Not like this ![Image](https://user-images.githubusercontent.com/159303/33674007-a3636e54-daae-11e7-91d8-465bb0cd5c70.png)

Anyway, nice start!

**Comment by jwensley2** [comment]
This will be in the next version.

Duplicate of #4.

**Comment by jwensley2** [comment]
There is a beta version now if you want to try this out.
https://addons.mozilla.org/en-US/firefox/addon/wx-download-status-bar/versions/beta?page=1#version-1.6.0beta1
