### ISSUE TITLE
Firefox 63 - I believe DSB need to be updated

### ISSUE THREAD

**Issue by Sopor-** [jwensley2/DownloadStatusBar#90]
After installing Firefox 63 the look of DSB have changed a lot to the bad. The proportion has change, i get a ugly red stop sign when trying to copy from the window.

**Comment by jwensley2** [comment]
Can you provide a screenshot? Personally I haven't noticed any difference from Firefox 62.

Firefox 63 finally turned on web components by default so I think I can fix a bunch of the styling issues you have reported just by wrapping the extension in a web component.

**Comment by Sopor-** [comment]
Sorry, my bad. It was happening right after i updated to version 63. I can now see it is sourceforge i get this on:

![image](https://user-images.githubusercontent.com/5789283/47609669-6cedfc00-da43-11e8-91e1-4b4ba37e2965.png)

https://sourceforge.net/projects/minibian/files/2016-03-12-jessie-minibian.tar.gz/download

**Comment by jwensley2** [comment]
Should be fixed in 1.9+
