### ISSUE TITLE
v1.9.0 update is breaking website CSS

### ISSUE THREAD

**Issue by HanFox** [jwensley2/DownloadStatusBar#91]
Using Firefox 63.

`[class^="icon-"], [class*=" icon-"], [class^="icon-"]::before, [class*=" icon-"]::before`

The above CSS is from DSB's content.css and is overwriting styles on one of my forums.

I have no idea how styling extensions can "leak" like that as I'd have thought they'd be sandboxed somehow.

Maybe you'll need to put all of your styles behind a certain id like #dsb instead?

**Comment by tsmith35** [comment]
Seeing the same thing here. Sites with specific icons are having the icons replaced with letters. Wouldn't have thought a browser status bar would break sites.

**Comment by jwensley2** [comment]
This should be fixed in 1.9.1, please update and let me know if it's still happening.

**Comment by HanFox** [comment]
Seems to be working correctly now. Thanks.
