### ISSUE TITLE
when moving the mouse to the popup windows it will close

### ISSUE THREAD

**Issue by Sopor-** [jwensley2/DownloadStatusBar#93]
When i hover the mouse pointer over my downloaded file a window will popup and show URL and other info but when i move the mouse to this popup windows to see the full download path the window close. So i can't copy Filename, URL or Referrer.

**Comment by Sopor-** [comment]
This is only half fixed. If i select the path and i want to copy it with the mouse button and open the context menu it will close and the copy won't work.

![image](https://user-images.githubusercontent.com/5789283/52312128-bc7c8600-29a9-11e9-9484-b10db0c6506e.png)

**Comment by jwensley2** [comment]
I'm not really sure how to fix the context menu issue so I'm going to add some copy buttons next to the path/urls. They should be faster to use than the context menu anyways.

**Comment by Sopor-** [comment]
But i'm sure it worked before. What has been changed?
